swagger: '2.0'
info:
  title: Date API
  description: API for getting date information
  version: 1.0.0
host: 127.0.0.1:8899
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /date:
    get:
      summary: Get date information
      description: Get date information in the specified format
      parameters:
        - name: format
          in: query
          type: string
          required: false
          description: Date format (1 - YYYYMMDD, 2 - YYYY-MM-DD)
      responses:
        '200':
          description: Date information
          schema:
            type: object
            properties:
              date:
                type: string
                example: 20231013
                description: Date information
        '400':
          description: Invalid request
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message